apiVersion: v1
kind: Service
metadata:
  name: {{ include "opus-admin-web.name" . }}
  namespace: {{ include "opus-admin-web.namespaceName" . }}
  labels:
    {{- include "opus-admin-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      protocol: TCP
      appProtocol: http
  selector:
    {{- include "opus-admin-web.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
