image:
  repository: docker.io/opusmvp/setup
  pullPolicy: Always
  tag: test
nodeSelector:
  "cloud.google.com/gke-nodepool": app
tolerations:
  - key: "app/app-reserved"
    operator: Exists
    effect: NoSchedule

mongo-main:
  enabled: false

opus-admin-web:
  image:
    repository: docker.io/opusmvp/admin-web
    pullPolicy: Always
    tag: test
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 150M

opus-authentication:
  image:
    repository: docker.io/opusmvp/authentication
    pullPolicy: Always
    tag: test
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 150M

opus-notification:
  image:
    repository: docker.io/opusmvp/notification
    pullPolicy: Always
    tag: test
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 150M

opus-user:
  image:
    repository: docker.io/opusmvp/user
    pullPolicy: Always
    tag: test
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 150M

opus-statistic:
  image:
    repository: docker.io/opusmvp/statistic
    pullPolicy: Always
    tag: test
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 150M

opus-payment:
  image:
    repository: docker.io/opusmvp/payment
    pullPolicy: Always
    tag: test
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 150M

opus-web:
  image:
    repository: docker.io/opusmvp/web
    pullPolicy: Always
    tag: test
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 150M
