image:
  repository: docker.io/opusintel/setup
  tag: 1.0.0
nodeSelector:
  "cloud.google.com/gke-nodepool": app
tolerations:
  - key: "app/app-reserved"
    operator: Exists
    effect: NoSchedule

mongo-main:
  enabled: false

opus-admin-web:
  image:
    repository: docker.io/opusintel/admin-web
    tag: 1.0.0
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 500M

opus-authentication:
  image:
    repository: docker.io/opusintel/authentication
    tag: 1.0.0
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 500M

opus-notification:
  image:
    repository: docker.io/opusintel/notification
    tag: 1.0.0
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 500M

opus-user:
  image:
    repository: docker.io/opusintel/user
    tag: 1.0.0
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 500M

opus-web:
  image:
    repository: docker.io/opusintel/web
    tag: 1.0.0
  nodeSelector:
    "cloud.google.com/gke-nodepool": app
  tolerations:
    - key: "app/app-reserved"
      operator: Exists
      effect: NoSchedule
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100M
    limits:
      cpu: 1000m
      memory: 500M
